### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by StrikeForceZero** [PrimeEuler/mib.js#2]
Could you add a license file to this project? MIT, BSD?

**Comment by bangert** [comment]
I would second this request.

**Comment by PrimeEuler** [comment]
Refactoring with pegjs parser and a modified grammer file from https://github.com/cederberg/mibble/blob/master/src/grammar/asn1.grammar.
License will be included. Early 2018 release.

**Comment by PrimeEuler** [comment]
Also thinking of using http://asn1js.org to compile the schema for serialization.

**Comment by PrimeEuler** [comment]
https://github.com/PrimeEuler/asn2json
ASN1 module parser complete with MIT license. 
SMI forder has working demo for MIB to JSON conversion. 
SMI/MIB.json is example output from parser.

TODO:
The compiler will use MIB.json and  asn1js for schema validation and serialization.
